In [66]:
import pandas as pd
import numpy as np

In [51]:
path = f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_summarize.csv"
df = pd.read_csv(path)

In [52]:
df.nlargest(1, "Average")

,Unnamed: 0,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
40,40,"Ensambler 3, GPT-4",0.905,0.602,0.892,0.888,0.677,0.808,0.796

In [56]:
ballad_summarize = pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_summarize.csv")
ballad_summarize = ballad_summarize[ballad_summarize["System"] != "Ensambler 3, GPT-4"]
ballad_summarize.nlargest(1, "Average")

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
28,"Chunk size 1000, 0%, K=7",0.911,0.826,0.636,0.884,0.913,0.522,0.782

In [55]:
ballad_report = pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_report.csv")
ballad_report = ballad_report[ballad_report["System"] != "Parent Retriever 500-100 -GPT4"]
ballad_report.nlargest(1, "Average")

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
28,Parent Retriever 500-100,0.929,0.9,0.614,0.613,0.884,0.621,0.76

In [47]:
ballad_qa = pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_qa.csv")
ballad_qa = ballad_qa[ballad_qa["System"] != "Ensambler 3, GPT-4"]
ballad_qa.nlargest(1, "Average")

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
35,Ensambler 3,0.615,0.723,0.802,0.403,0.612,0.622,0.629

In [40]:
papers_error = pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/papers/results/results_errors.csv")
papers_error=papers_error[papers_error["System"] != "Chunk size 500, overlap 20%, K=3, GPT-4"]
papers_error.nlargest(1, "Average")

,System,Context Precision,Context Recall,Accuracy,Average
7,"Chunk 500, overlap 15%",0.872,0.9,0.4,0.724

In [32]:
news_qa = pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/news/results/results_qa_news.csv")
news_qa = news_qa[news_qa["System"] != "Chunk 1000, overlap 0%, GPT-4"]
news_qa.nlargest(1, "Average")

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
13,"Chunk 1000, overlap 20%",1.0,0.889,0.883,0.98,0.921,0.609,0.88

In [67]:
missing = pd.DataFrame({
        "System": ["GPT-3.5", "GPT-4"],
        "Faithfulness": [np.nan, 0.863],
        "Answer Relevancy": [np.nan, 0.883],
        "Context Precision": [np.nan, np.nan],
        "Context Recall": [np.nan, np.nan],
        "Answer Similarity": [np.nan, 0.858],
        "Answer Correctness": [np.nan, 0.660],
        "Average": [ 0.697, 0.816]
    })

In [69]:
ballad_report = ballad_report.append(missing)
ballad_report

C:\Users\sigit\AppData\Local\Temp\ipykernel_900\750013423.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ballad_report = ballad_report.append(missing)

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
0,Naive,0.840,0.726,0.512,0.764,0.755,0.805,0.734
1,Recursive,0.840,0.721,0.456,0.542,0.789,0.802,0.692
2,"Chunk 500, overlap 0%",0.785,0.717,0.493,0.653,0.678,0.804,0.688
3,"Chunk 500, overlap 5%",0.894,0.736,0.471,0.802,0.678,0.814,0.732
4,"Chunk 500, overlap 10%",0.871,0.744,0.471,0.579,0.700,0.698,0.677
5,"Chunk 500, overlap 15%",0.873,0.733,0.562,0.686,0.679,0.806,0.723
6,"Chunk 500, overlap 20%",0.895,0.736,0.512,0.575,0.678,0.809,0.701
7,"Chunk 1000, overlap 0%",0.873,0.733,0.521,0.686,0.679,0.805,0.716
8,"Chunk 1000, overlap 5%",0.870,0.739,0.471,0.801,0.678,0.800,0.726
9,"Chunk 1000, overlap 10%",0.874,0.741,0.512,0.579,0.678,0.800,0.697
10,"Chunk 1000, overlap 15%",0.815,0.717,0.512,0.762,0.678,0.806,0.715
11,"Chunk 1000, overlap 20%",0.785,0.739,0.456,0.579,0.678,0.661,0.650
12,"Chunk 2000, overlap 0%",0.876,0.722,0.512,0.797,0.678,0.806,0.732
13,"Chunk 2000, overlap 5%",0.863,0.706,0.512,0.649,0.737,0.761,0.705
14,"Chunk 2000, overlap 10%",0.896,0.723,0.637,0.580,0.679,0.806,0.720
15,"Chunk 2000, overlap 15%",0.875,0.717,0.519,0.691,0.706,0.798,0.718
16,"Chunk 2000, overlap 20%",0.871,0.739,0.471,0.802,0.685,0.809,0.730
17,"Chunk 3000, overlap 0%",0.873,0.729,0.452,0.802,0.678,0.800,0.722
18,"Chunk 3000, overlap 5%",0.894,0.716,0.474,0.579,0.678,0.809,0.692
19,"Chunk 3000, overlap 10%",0.896,0.722,0.637,0.801,0.678,0.806,0.757
20,"Chunk 3000, overlap 15%",0.875,0.733,0.512,0.576,0.790,0.806,0.715
21,"Chunk 3000, overlap 20%",0.839,0.723,0.471,0.653,0.678,0.812,0.696
22,"Chunk size 3000, 20%, K=2",0.850,0.791,0.444,0.796,0.872,0.582,0.723
23,"Chunk size 3000, 20%, K=3",0.667,0.906,0.444,0.694,0.872,0.651,0.706
24,"Chunk size 3000, 20%, K=5",0.836,0.899,0.408,0.639,0.875,0.639,0.716
25,"Chunk size 3000, 20%, K=6",0.852,0.882,0.416,0.694,0.870,0.644,0.726
26,"Chunk size 3000, 20%, K=7",0.935,0.752,0.555,0.810,0.717,0.545,0.719
27,Parent Retriever 1000-200,0.887,0.627,0.667,0.710,0.721,0.764,0.729
28,Parent Retriever 500-100,0.929,0.900,0.614,0.613,0.884,0.621,0.760
29,MMR,0.865,0.757,0.561,0.690,0.737,0.615,0.704
30,BM25,0.821,0.886,0.537,0.667,0.883,0.580,0.729
31,Ensambler 1,0.922,0.738,0.620,0.629,0.782,0.713,0.734
32,Ensambler 2,0.887,0.720,0.657,0.590,0.792,0.796,0.740
33,Ensambler 3,1.000,0.868,0.392,0.628,0.879,0.664,0.738
34,Parent Retriever 1500-200,0.850,0.662,0.444,0.556,0.849,0.491,0.642
35,Search query,0.812,0.884,0.414,0.444,0.862,0.594,0.668
37,"Chunk 3000, overlap 10%, GPT4",0.909,0.746,0.442,0.561,0.677,0.796,0.688
38,"Ensambler 2, GPT-4",0.823,0.710,0.615,0.630,0.681,0.782,0.707
0,GPT-3.5,NaN,NaN,NaN,NaN,NaN,NaN,0.697
1,GPT-4,0.863,0.883,NaN,NaN,0.858,0.660,0.816

In [84]:
ballad_report.to_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_report.csv", index = False)

In [82]:
dataframes = [
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/papers/results/results_qa.csv"),
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/papers/results/results_reporting.csv"),
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/papers/results/results_summarize.csv"),
    papers_error,
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/news/results/results_errors.csv"),
    news_qa,
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/news/results/results_reporting.csv"),
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/news/results/results_summary.csv"),
    pd.read_csv(f"C:/Users/sigit/OneDrive/TSI/thesis/thesis-rag/ballad/results/results_errors.csv"),
    ballad_qa,
    ballad_report,
    ballad_summarize
]

In [72]:
len(dataframes)

12

In [91]:
ballad_report

,System,Faithfulness,Answer Relevancy,Context Precision,Context Recall,Answer Similarity,Answer Correctness,Average
0,Naive,0.840,0.726,0.512,0.764,0.755,0.805,0.734
1,Recursive,0.840,0.721,0.456,0.542,0.789,0.802,0.692
2,"Chunk 500, overlap 0%",0.785,0.717,0.493,0.653,0.678,0.804,0.688
3,"Chunk 500, overlap 5%",0.894,0.736,0.471,0.802,0.678,0.814,0.732
4,"Chunk 500, overlap 10%",0.871,0.744,0.471,0.579,0.700,0.698,0.677
5,"Chunk 500, overlap 15%",0.873,0.733,0.562,0.686,0.679,0.806,0.723
6,"Chunk 500, overlap 20%",0.895,0.736,0.512,0.575,0.678,0.809,0.701
7,"Chunk 1000, overlap 0%",0.873,0.733,0.521,0.686,0.679,0.805,0.716
8,"Chunk 1000, overlap 5%",0.870,0.739,0.471,0.801,0.678,0.800,0.726
9,"Chunk 1000, overlap 10%",0.874,0.741,0.512,0.579,0.678,0.800,0.697
10,"Chunk 1000, overlap 15%",0.815,0.717,0.512,0.762,0.678,0.806,0.715
11,"Chunk 1000, overlap 20%",0.785,0.739,0.456,0.579,0.678,0.661,0.650
12,"Chunk 2000, overlap 0%",0.876,0.722,0.512,0.797,0.678,0.806,0.732
13,"Chunk 2000, overlap 5%",0.863,0.706,0.512,0.649,0.737,0.761,0.705
14,"Chunk 2000, overlap 10%",0.896,0.723,0.637,0.580,0.679,0.806,0.720
15,"Chunk 2000, overlap 15%",0.875,0.717,0.519,0.691,0.706,0.798,0.718
16,"Chunk 2000, overlap 20%",0.871,0.739,0.471,0.802,0.685,0.809,0.730
17,"Chunk 3000, overlap 0%",0.873,0.729,0.452,0.802,0.678,0.800,0.722
18,"Chunk 3000, overlap 5%",0.894,0.716,0.474,0.579,0.678,0.809,0.692
19,"Chunk 3000, overlap 10%",0.896,0.722,0.637,0.801,0.678,0.806,0.757
20,"Chunk 3000, overlap 15%",0.875,0.733,0.512,0.576,0.790,0.806,0.715
21,"Chunk 3000, overlap 20%",0.839,0.723,0.471,0.653,0.678,0.812,0.696
22,"Chunk size 3000, 20%, K=2",0.850,0.791,0.444,0.796,0.872,0.582,0.723
23,"Chunk size 3000, 20%, K=3",0.667,0.906,0.444,0.694,0.872,0.651,0.706
24,"Chunk size 3000, 20%, K=5",0.836,0.899,0.408,0.639,0.875,0.639,0.716
25,"Chunk size 3000, 20%, K=6",0.852,0.882,0.416,0.694,0.870,0.644,0.726
26,"Chunk size 3000, 20%, K=7",0.935,0.752,0.555,0.810,0.717,0.545,0.719
27,Parent Retriever 1000-200,0.887,0.627,0.667,0.710,0.721,0.764,0.729
28,Parent Retriever 500-100,0.929,0.900,0.614,0.613,0.884,0.621,0.760
29,MMR,0.865,0.757,0.561,0.690,0.737,0.615,0.704
30,BM25,0.821,0.886,0.537,0.667,0.883,0.580,0.729
31,Ensambler 1,0.922,0.738,0.620,0.629,0.782,0.713,0.734
32,Ensambler 2,0.887,0.720,0.657,0.590,0.792,0.796,0.740
33,Ensambler 3,1.000,0.868,0.392,0.628,0.879,0.664,0.738
34,Parent Retriever 1500-200,0.850,0.662,0.444,0.556,0.849,0.491,0.642
35,Search query,0.812,0.884,0.414,0.444,0.862,0.594,0.668
37,"Chunk 3000, overlap 10%, GPT4",0.909,0.746,0.442,0.561,0.677,0.796,0.688
38,"Ensambler 2, GPT-4",0.823,0.710,0.615,0.630,0.681,0.782,0.707
0,GPT-3.5,NaN,NaN,NaN,NaN,NaN,NaN,0.697
1,GPT-4,0.863,0.883,NaN,NaN,0.858,0.660,0.816

In [88]:
difference_values = []

# Iterate through each dataframe
for df in dataframes:
    # Find the maximum value in the "Average" column
    max_avg_value = df["Average"].max()
    # Find the average value corresponding to GPT-3.5
    avg_gpt35 = float(df[df["System"] == "GPT-3.5"]["Average"])
    # Calculate the difference and append it to the list
    difference_values.append(max_avg_value - avg_gpt35)

# # Calculate the average of all the difference values
average_difference = sum(difference_values) / len(difference_values)

print("Average difference between max value and average value of GPT-3.5 across all dataframes:", average_difference)

[0.28]
[0.28, 0.08200000000000007]
[0.28, 0.08200000000000007, 0.21800000000000008]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997, 0.29000000000000004]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997, 0.29000000000000004, 0.619]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997, 0.29000000000000004, 0.619, 0.238]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997, 0.29000000000000004, 0.619, 0.238, 0.119]
[0.28, 0.08200000000000007, 0.21800000000000008, 0.724, 0.796, 0.255, 0.21699999999999997, 0.29000000000000004, 0.619, 0.238, 0.119, 0.118]
Average difference between max value and average value of GPT-3.5 across all dataframes: 0.3296666666666667